version: '3'
services:
  tomcat:
    image: tomcat:10.0-jdk17-openjdk
    ports:
      - "8888:8080"
      - "5005:5005"
    volumes:
      - ./target:/usr/local/tomcat/webapps
    environment:
      - agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    command: [ "catalina.sh", "run" ]
